import { describe, it, expect } from "vitest";
import { loadSpecs } from "../src/loader.js";
import { loadPrinciples } from "../src/principles.js";
import { generateAgentInstructions } from "../src/agent.js";
import { mkdtempSync, writeFileSync, mkdirSync } from "fs";
import { join } from "path";
import { tmpdir } from "os";

describe("agent instructions integration", () => {
  it("generates complete instructions from specs and principles on disk", () => {
    const dir = mkdtempSync(join(tmpdir(), "sps-agent-test-"));

    // Create .sps/principles.yaml
    mkdirSync(join(dir, ".sps"));
    writeFileSync(
      join(dir, ".sps/principles.yaml"),
      `principles:\n  - id: money-in-cents\n    title: "Money in cents"\n    description: "All monetary values are integers in cents."\n`
    );

    // Create two spec files
    mkdirSync(join(dir, "src/checkout/coupons"), { recursive: true });
    writeFileSync(
      join(dir, "src/checkout/coupons/coupons.sps.yaml"),
      `spec: checkout/coupons
title: "Discount Codes"
description: "Coupon support at checkout"
category: business
touches: [billing]
rules:
  - id: REQ-CHECKOUT-COUPON-01
    title: "Apply percentage coupon"
    status: active
    category: business
    description: "Reduces cart by percentage"
    given: "Cart is $100, coupon SAVE20 is 20% off"
    when: "Customer applies coupon"
    then: "Cart becomes $80"
    examples: []
    edge_cases:
      - case: "100% discount"
        decision: "Cart total becomes $0"
    tests: []
  - id: REQ-CHECKOUT-COUPON-02
    title: "Reject expired coupon"
    status: active
    category: business
    description: "Expired coupons are rejected"
    given: "Coupon expired yesterday"
    when: "Customer applies expired coupon"
    then: "Error shown, cart unchanged"
    examples: []
    edge_cases: []
    tests: []
`
    );

    mkdirSync(join(dir, "src/billing"), { recursive: true });
    writeFileSync(
      join(dir, "src/billing/billing.sps.yaml"),
      `spec: billing
title: "Billing"
description: "Invoice management"
category: engineering
touches: []
rules:
  - id: REQ-BIL-INV-01
    title: "Generate invoice on order completion"
    status: active
    category: engineering
    description: "Creates invoice when order is placed"
    given: "An order is completed"
    when: "Payment is confirmed"
    then: "Invoice is generated and emailed"
    examples: []
    edge_cases: []
    tests: []
  - id: REQ-BIL-INV-02
    title: "Old billing rule"
    status: deprecated
    category: engineering
    description: "Deprecated rule"
    given: "N/A"
    when: "N/A"
    then: "N/A"
    examples: []
    edge_cases: []
    tests: []
`
    );

    // Load and generate
    const specs = loadSpecs(dir);
    const principles = loadPrinciples(dir);
    const output = generateAgentInstructions(specs, principles);

    // Verify structure
    expect(output).toContain("# SPS Spec Rules");
    expect(output).toContain("Auto-generated by `sps agent`");

    // Verify principles
    expect(output).toContain("## Principles");
    expect(output).toContain("Money in cents");
    expect(output).toContain("integers in cents");

    // Verify active rules from checkout/coupons
    expect(output).toContain("checkout/coupons");
    expect(output).toContain("Discount Codes");
    expect(output).toContain("touches: billing");
    expect(output).toContain("REQ-CHECKOUT-COUPON-01");
    expect(output).toContain("Apply percentage coupon");
    expect(output).toContain("Cart is $100");
    expect(output).toContain("REQ-CHECKOUT-COUPON-02");
    expect(output).toContain("Reject expired coupon");

    // Verify edge cases included
    expect(output).toContain("100% discount");

    // Verify test linking instructions
    expect(output).toContain("[REQ-CHECKOUT-COUPON-01]");

    // Verify billing spec
    expect(output).toContain("billing");
    expect(output).toContain("REQ-BIL-INV-01");
    expect(output).toContain("Generate invoice on order completion");

    // Verify deprecated rule is excluded
    expect(output).not.toContain("REQ-BIL-INV-02");
    expect(output).not.toContain("Old billing rule");

    // Verify it found the right number of specs
    expect(specs).toHaveLength(2);
    expect(principles).toHaveLength(1);
  });
});
