import type { SpecFile } from "./types.js";
import type { Principle } from "./principles.js";

export function generateAgentInstructions(
  specs: SpecFile[],
  principles: Principle[]
): string {
  const lines: string[] = [];

  lines.push("# SPS Spec Rules");
  lines.push("");
  lines.push("> Auto-generated by `sps agent`. Do not edit manually.");
  lines.push("> Run `sps agent` to regenerate after spec changes.");
  lines.push("");

  if (principles.length > 0) {
    lines.push("## Principles");
    lines.push("");
    for (const p of principles) {
      lines.push(`- **${p.title}** — ${p.description}`);
    }
    lines.push("");
  }

  const activeSpecs = specs.filter((s) =>
    s.rules.some((r) => r.status === "active" || r.status === "proposed")
  );

  if (activeSpecs.length === 0) {
    lines.push("No active spec rules found. Run `sps submit` to create specs.");
    return lines.join("\n");
  }

  lines.push("## Active Rules");
  lines.push("");

  for (const spec of activeSpecs) {
    const touchesStr = spec.touches.length > 0
      ? ` (touches: ${spec.touches.join(", ")})`
      : "";
    lines.push(`### ${spec.spec} — ${spec.title}${touchesStr}`);
    lines.push("");

    const activeRules = spec.rules.filter(
      (r) => r.status === "active" || r.status === "proposed"
    );

    for (const rule of activeRules) {
      const status = rule.status === "proposed" ? " [PROPOSED]" : "";
      lines.push(`- **${rule.id}** ${rule.title}${status}`);
      lines.push(`  - Given: ${rule.given}`);
      lines.push(`  - When: ${rule.when}`);
      lines.push(`  - Then: ${rule.then}`);

      if (rule.edge_cases.length > 0) {
        for (const ec of rule.edge_cases) {
          lines.push(`  - Edge case: ${ec.case} → ${ec.decision}`);
        }
      }

      if (rule.id) {
        lines.push(`  - Tests: Link test describe blocks with \`[${rule.id}]\``);
      }

      lines.push("");
    }
  }

  return lines.join("\n");
}
