import { simpleGit } from "simple-git";
import { writeFileSync, mkdirSync } from "fs";
import { join, dirname } from "path";
import type { SpsConfig, TraceBlock } from "./types.js";

export async function createSpecBranch(
  repoRoot: string,
  filePath: string,
  content: string,
  config: SpsConfig,
  slug: string
): Promise<{ branch: string }> {
  const git = simpleGit(repoRoot);
  const branch = `${config.git.branch_prefix}${slug}`;

  await git.checkoutLocalBranch(branch);

  const fullPath = join(repoRoot, filePath);
  mkdirSync(dirname(fullPath), { recursive: true });
  writeFileSync(fullPath, content, "utf-8");

  await git.add(filePath);
  await git.commit(`${config.git.commit_prefix} add ${filePath}`);

  if (config.git.create_pr) {
    await git.push("origin", branch, ["--set-upstream"]);
  }

  return { branch };
}

export function buildPrDescription(
  trace: TraceBlock,
  specName: string,
  ruleCount: number
): string {
  return `## New Spec: ${specName}

**${ruleCount} rules** generated from a requirement submission.

### Requirement
> ${trace.original_text}

### Traceability
| Field | Value |
|-------|-------|
| Requested by | ${trace.requested_by} |
| Submitted via | ${trace.source} |
| Interpreted by | ${trace.interpretation_model} |
| Submitted at | ${trace.requested_at} |

### Related Specs
${trace.related_specs.length === 0 ? "None found." : trace.related_specs.map((r) => `- ${r.id} (${r.relationship}): ${r.note}`).join("\n")}

---
*Generated by [SPS](https://github.com/sps/sps) — Spec, Plan, Ship*`;
}
